// hunt-reward-flow 화면에서 사용하는 Figma export 에셋 경로 모음
const BASE = "/assets";

export const HUNT_ASSETS = {
  icons: {
    backArrow: `${BASE}/icons/nav/icon_nav_back_arrow_rough_default_18.svg`,
    gnbBell: `${BASE}/icons/gnb/icon_gnb_bell_rough_default_20.svg`,
    gnbHelp: `${BASE}/icons/gnb/icon_gnb_help_circle_rough_default_20.svg`,
    gnbSettings: `${BASE}/icons/gnb/icon_gnb_settings_rough_default_20.svg`,
    tabMapBlack: `${BASE}/icons/tab/icon_tab_map_pin_black_20.svg`,
    tabMapWhite: `${BASE}/icons/tab/icon_tab_map_pin_white_20.svg`,
    tabHuntBlack: `${BASE}/icons/tab/icon_tab_hunt_black_20.svg`,
    tabHuntWhite: `${BASE}/icons/tab/icon_tab_hunt_white_20.svg`,
    tabRankBlack: `${BASE}/icons/tab/icon_tab_rank_trophy_black_18.svg`,
    tabMyInfoBlack: `${BASE}/icons/tab/icon_tab_myinfo_person_black_16.svg`,
    tabMyInfoWhite: `${BASE}/icons/tab/icon_tab_myinfo_person_white_16.svg`,
    mapBannerBell: `${BASE}/icons/map/icon_map_banner_bell_white_20.svg`,
    mapCrosshair: `${BASE}/icons/map/icon_map_crosshair_rough_default_22.svg`,
    mapRefresh: `${BASE}/icons/map/icon_map_refresh_rough_default_16.svg`,
    closeCircle: `${BASE}/icons/action/icon_action_close_circle_rough_default_24.svg`,
    arrowRightBlack: `${BASE}/icons/action/icon_action_arrow_right_black_18.svg`,
    arrowRightWhite: `${BASE}/icons/action/icon_action_arrow_right_white_18.svg`,
    arTapTarget: `${BASE}/icons/ar/icon_ar_tap_target_red_32.svg`,
    resultHuntLogRefresh: `${BASE}/icons/result/icon_result_hunt_log_refresh_12.svg`,
    resultFailBadge: `${BASE}/icons/result/icon_result_fail_badge_rough_default.svg`,
    resultFailHouse: `${BASE}/icons/result/icon_result_fail_empty_house_rough_default.svg`,
    resultFailSadFace: `${BASE}/icons/result/icon_result_fail_sad_face_rough_default.svg`,
    inventoryTitleBox: `${BASE}/icons/inventory/icon_inventory_title_box_rough_default_32.svg`,
    inventoryErrorCircle: `${BASE}/icons/inventory/icon_inventory_error_circle_red_25.svg`,
    inventoryRetry: `${BASE}/icons/inventory/icon_inventory_retry_red_16.svg`,
    inventoryCheckCircle: `${BASE}/icons/inventory/icon_inventory_check_circle_gray_20.svg`,
    inventoryChevronRight: `${BASE}/icons/inventory/icon_inventory_chevron_right_12.svg`,
  },
  markers: {
    yellow: `${BASE}/markers/map/marker_treasure_box_yellow_shadow_40.svg`,
    purple: `${BASE}/markers/map/marker_treasure_box_purple_shadow_40.svg`,
    claimed: `${BASE}/markers/map/marker_treasure_box_claimed_40.svg`,
  },
  frames: {
    ctaBlack: `${BASE}/ui/frames/global/ui_frame_cta_button_black_rough_default.svg`,
    ctaWhite: `${BASE}/ui/frames/global/ui_frame_cta_button_white_rough_default.svg`,
    ctaWhiteWide: `${BASE}/ui/frames/global/ui_frame_cta_button_white_wide_rough_default.svg`,
    hintPopupSheet: `${BASE}/ui/frames/treasure/ui_frame_treasure_hint_popup_sheet_rough_default.svg`,
    hintPopup: `${BASE}/ui/frames/treasure/ui_frame_treasure_hint_popup_rough_default.svg`,
    hintCtaChip: `${BASE}/ui/frames/treasure/ui_frame_filter_chip_active_sm_rough_default.svg`,
    distanceInfo: `${BASE}/ui/frames/treasure/ui_frame_treasure_distance_info_rough_default.svg`,
    guideStepCardEven: `${BASE}/ui/frames/treasure/ui_frame_guide_step_card_even_rough_default.svg`,
    arInstructionBubble: `${BASE}/ui/frames/ar/ui_frame_ar_instruction_bubble_rough_default.svg`,
    resultSuccessCardFill: `${BASE}/ui/frames/result/ui_frame_result_success_reward_card_fill_rough_default.svg`,
    resultSuccessCardStroke: `${BASE}/ui/frames/result/ui_frame_result_success_reward_card_stroke_rough_default.svg`,
    resultFailCardFill: `${BASE}/ui/frames/result/ui_frame_result_fail_empty_card_fill_rough_default.svg`,
    resultFailCardStroke: `${BASE}/ui/frames/result/ui_frame_result_fail_empty_card_stroke_rough_default.svg`,
    grugQuoteDivider: `${BASE}/ui/frames/result/ui_divider_grug_quote_rough_default.svg`,
    inventoryCardOdd: `${BASE}/ui/frames/inventory/ui_frame_guide_step_card_odd_rough_default.svg`,
    inventoryCardFailed: `${BASE}/ui/frames/inventory/ui_frame_inventory_reward_card_failed_rough_default.svg`,
    rewardDetailCard: `${BASE}/ui/frames/reward-detail/ui_frame_reward_detail_barcode_box_rough_default.svg`,
    rewardDetailCloseButton: `${BASE}/ui/frames/reward-detail/ui_frame_profile_logout_button_white_rough_default.svg`,
  },
  images: {
    mapMockBg: `${BASE}/images/map/img_map_mock_bg.png`,
    arMockBg: `${BASE}/images/ar/img_ar_mock_bg.png`,
    rewardCoffee: `${BASE}/images/inventory/img_inventory_reward_coffee.png`,
    rewardSandwich: `${BASE}/images/inventory/img_inventory_reward_sandwich.png`,
    resultRewardCoffee: `${BASE}/images/result/img_result_reward_coffee.png`,
  },
} as const;
